### ISSUE TITLE
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

### ISSUE THREAD

**Issue by iehsan77** [jconst/JCDialPad#2]
PhaseScriptExecution Check\ Pods\ Manifest.lock /Users/EhsanUlHaq/Library/Developer/Xcode/DerivedData/JCDialPadDemo-evtyshmfocntfvelcuqhvpsmeccz/Build/Intermediates/JCDialPadDemo.build/Debug-iphonesimulator/JCDialPadDemo.build/Script-8AA3BADFC8B54D8790496D3E.sh
    cd "/Users/EhsanUlHaq/Desktop/SuperTech Final Projects/MIK Dialer Project/JCDialPad-master/JCDialPadDemo"
    /bin/sh -c /Users/EhsanUlHaq/Library/Developer/Xcode/DerivedData/JCDialPadDemo-evtyshmfocntfvelcuqhvpsmeccz/Build/Intermediates/JCDialPadDemo.build/Debug-iphonesimulator/JCDialPadDemo.build/Script-8AA3BADFC8B54D8790496D3E.sh

diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

where is the missing files 

how i can use these or install it. is there any docu

thanks

**Comment by benslamajihed** [comment]
i try  to  integrate cocoapod  with  old  project and  i get  the  same  problem with Xcode 7 and 0.38.2 pod version. i follow  right  steps  to  integrate it  but  i always  have  same  error  :/
